// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from './deno.json' assert { type: 'json' }
import * as $0 from './routes/[name].tsx'
import * as $1 from './routes/api/joke.ts'
import * as $2 from './routes/api/optimize/[url].ts'
import * as $3 from './routes/api/zip.ts'
import * as $4 from './routes/index.tsx'
import * as $5 from './routes/optimize/[url].tsx'
import * as $$0 from './islands/App.tsx'

const manifest = {
    routes: {
        './routes/[name].tsx': $0,
        './routes/api/joke.ts': $1,
        './routes/api/optimize/[url].ts': $2,
        './routes/api/zip.ts': $3,
        './routes/index.tsx': $4,
        './routes/optimize/[url].tsx': $5,
    },
    islands: {
        './islands/App.tsx': $$0,
    },
    baseUrl: import.meta.url,
    config,
}

export default manifest
